# countries.py
from typing import Dict

def norm_country(s: str) -> str:
    # нормализуем пробелы, регистр, апострофы и диакритику (минимально)
    s = (s or "").strip()
    s = " ".join(s.split())
    # унифицируем популярные варианты
    repl = {
        "Cote d'Ivoire": "Côte d'Ivoire",
        "Cote d’Ivoire": "Côte d'Ivoire",
        "Côte d’Ivoire": "Côte d'Ivoire",
    }
    return repl.get(s, s)

# ключи — РОВНО как в датасете (после norm_country)
COUNTRY_TO_CONTINENT: Dict[str, str] = {
    # ---------- EUROPE ----------
    "France": "europe",
    "Norway": "europe",
    "Belgium": "europe",
    "Poland": "europe",
    "England": "europe",
    "Spain": "europe",
    "Portugal": "europe",
    "Germany": "europe",
    "Netherlands": "europe",
    "Slovenia": "europe",
    "Italy": "europe",
    "Switzerland": "europe",
    "Croatia": "europe",
    "Georgia": "europe",
    "Scotland": "europe",
    "Serbia": "europe",
    "Austria": "europe",
    "Denmark": "europe",
    "Hungary": "europe",
    "Slovakia": "europe",
    "Czech Republic": "europe",
    "Bosnia and Herzegovina": "europe",
    "Ukraine": "europe",
    "Montenegro": "europe",
    "Sweden": "europe",
    "Greece": "europe",
    "Finland": "europe",
    "Armenia": "europe",
    "Kosovo": "europe",
    "North Macedonia": "europe",
    "Russia": "europe",
    "Malta": "europe",
    "Albania": "europe",
    "Wales": "europe",
    "Romania": "europe",
    "Republic of Ireland": "europe",
    "Luxembourg": "europe",
    "Bulgaria": "europe",
    "Iceland": "europe",
    "Northern Ireland": "europe",
    "Moldova": "europe",
    "Cyprus": "europe",
    "Estonia": "europe",
    "Liechtenstein": "europe",
    "Andorra": "europe",
    "Latvia": "europe",
    "Lithuania": "europe",
    "Belarus": "europe",
    "Faroe Islands": "europe",
    "Gibraltar": "europe",
    "San Marino": "europe",

    # ---------- SOUTH AMERICA ----------
    "Argentina": "south_america",
    "Brazil": "south_america",
    "Uruguay": "south_america",
    "Colombia": "south_america",
    "Chile": "south_america",
    "Paraguay": "south_america",
    "Ecuador": "south_america",
    "Peru": "south_america",
    "Suriname": "south_america",
    "Venezuela": "south_america",
    "Bolivia": "south_america",
    "Guyana": "south_america",

    # ---------- NORTH AMERICA (incl. Central America + Caribbean) ----------
    "Costa Rica": "north_america",
    "Canada": "north_america",
    "Mexico": "north_america",
    "United States": "north_america",
    "Jamaica": "north_america",
    "Trinidad and Tobago": "north_america",
    "Dominican Republic": "north_america",
    "Haiti": "north_america",
    "Curacao": "north_america",
    "Panama": "north_america",
    "Cuba": "north_america",
    "Grenada": "north_america",
    "Bermuda": "north_america",
    "Guatemala": "north_america",
    "El Salvador": "north_america",
    "Saint Lucia": "north_america",
    "Saint Kitts and Nevis": "north_america",
    "Antigua and Barbuda": "north_america",
    "Puerto Rico": "north_america",
    "Montserrat": "north_america",
    "Belize": "north_america",
    "Aruba": "north_america",
    "Nicaragua": "north_america",
    "Honduras": "north_america",
    "Barbados": "north_america",
    "Saint Vincent and the Grenadines": "north_america",

    # ---------- AFRICA ----------
    "Egypt": "africa",
    "Nigeria": "africa",
    "Algeria": "africa",
    "Senegal": "africa",
    "Cameroon": "africa",
    "Morocco": "africa",
    "Ghana": "africa",
    "Tunisia": "africa",
    "Libya": "africa",
    "Central African Republic": "africa",
    "Mozambique": "africa",
    "Congo DR": "africa",
    "Gabon": "africa",
    "Mali": "africa",
    "Angola": "africa",
    "Guinea": "africa",
    "Togo": "africa",
    "Gambia": "africa",
    "Zimbabwe": "africa",
    "Liberia": "africa",
    "Equatorial Guinea": "africa",
    "Burundi": "africa",
    "Zambia": "africa",
    "Cape Verde Islands": "africa",
    "Guinea Bissau": "africa",
    "Kenya": "africa",
    "South Africa": "africa",
    "Comoros": "africa",
    "Benin": "africa",
    "Madagascar": "africa",
    "Congo": "africa",
    "Tanzania": "africa",
    "Uganda": "africa",
    "Chad": "africa",
    "Sierra Leone": "africa",
    "Mauritania": "africa",
    "Ethiopia": "africa",
    "Mauritius": "africa",
    "Sudan": "africa",
    "Malawi": "africa",
    "Namibia": "africa",
    "São Tomé e Príncipe": "africa",
    "South Sudan": "africa",
    "Niger": "africa",
    "Eritrea": "africa",
    "Rwanda": "africa",
    "Somalia": "africa",
    "Swaziland": "africa",
    "Burkina Faso": "africa",
    "Côte d'Ivoire": "africa",

    # ---------- ASIA ----------
    "Korea Republic": "asia",
    "Iran": "asia",
    "Japan": "asia",
    "Turkey": "asia",
    "Israel": "asia",
    "Saudi Arabia": "asia",
    "China PR": "asia",
    "Qatar": "asia",
    "Palestine": "asia",
    "Uzbekistan": "asia",
    "United Arab Emirates": "asia",
    "Azerbaijan": "asia",
    "Jordan": "asia",
    "Kazakhstan": "asia",
    "Chinese Taipei": "asia",
    "Philippines": "asia",
    "Iraq": "asia",
    "Hong Kong": "asia",
    "India": "asia",
    "Syria": "asia",
    "Indonesia": "asia",
    "Sri Lanka": "asia",
    "Pakistan": "asia",
    "Korea DPR": "asia",
    "Thailand": "asia",
    "Lebanon": "asia",
    "Nepal": "asia",
    "Vietnam": "asia",
    "Afghanistan": "asia",
    "Singapore": "asia",
    "Kyrgyzstan": "asia",
    "Bhutan": "asia",
    "Malaysia": "asia",
    "Macau": "asia",
    "Bahrain": "asia",
    "Oman": "asia",
    "Kuwait": "asia",
    "Turkmenistan": "asia",
    "Brunei Darussalam": "asia",
    "Tajikistan": "asia",
    "Timor-Leste": "asia",
    "Cambodia": "asia",

    # ---------- OCEANIA ----------
    "Australia": "oceania",
    "New Zealand": "oceania",
    "Fiji": "oceania",
    "Vanuatu": "oceania",
    "Papua New Guinea": "oceania",
    "Guam": "oceania",
    "New Caledonia": "oceania",
}
